/// This trait provides a way to convert a struct into a struct containing only `untrusted_value::UntrustedValue` fields
/// as generated by the `#[derive(UntrustedVariant)]` macro.
pub trait IntoUntrustedVariant<Insecure, Trusted>
where
    Insecure: SanitizeWith<Insecure, Trusted>,
{
    /// Returns a wrapped variant of the struct, containing only
    /// `untrusted_value::UntrustedValue` fields.
    ///
    /// An instance of a struct like this:
    /// ```ignore
    /// #[derive(UntrustedVariant)]
    /// pub struct Example {
    ///    pub name: String,
    /// }
    /// ```
    ///
    /// will be turned into an instance of:
    /// ```rust
    /// # use untrusted_value::UntrustedValue;
    /// pub struct ExampleUntrusted {
    ///   pub name: UntrustedValue<String>,
    /// }
    /// ```
    fn to_untrusted_variant(self) -> Insecure;
}

/// This type can be sanitized using a provided sanitizer.
///
/// This trait will be implemented automatically for structs
/// generated by the `#[derive(UntrustedVariant)]` macro.
pub trait SanitizeWith<Insecure, Trusted> {
    /// Sanitizes the value using the provided sanitizer.
    ///
    /// If sanitization fails, an error must be returned.
    fn sanitize_with<Sanitizer, Error>(self, sanitizer: Sanitizer) -> Result<Trusted, Error>
    where
        Sanitizer: FnOnce(Insecure) -> Result<Trusted, Error>;
}

/// The type implementing this struct can be sanitized.
///
/// Calling `sanitize_value()` on the implementing type should return a sanitized version of the value.
/// If the value cannot be sanitized, an error should be returned.
pub trait SanitizeValue<Trusted> {
    type Error;

    /// Sanitizes the value.
    /// The returned value might be of a different type.
    ///
    /// The returned value is sanitized and can be safely used.
    /// If the value cannot be sanitized, an error must be returned.
    fn sanitize_value(self) -> Result<Trusted, Self::Error>;
}
