/// This type can be sanitized using a provided sanitizer.
///
/// This trait will be implemented automatically for structs
/// generated by the `#[derive(UntrustedVariant)]` macro.
///
/// The `sanitize_with` function SHOULD clear all taint from the input.
pub trait SanitizeWith<Insecure, Trusted> {
    /// Sanitizes the value using the provided sanitizer.
    ///
    /// # Errors
    /// If sanitization fails, an error must be returned.
    fn sanitize_with<Sanitizer, Error>(self, sanitizer: Sanitizer) -> Result<Trusted, Error>
    where
        Sanitizer: FnOnce(Insecure) -> Result<Trusted, Error>;
}
